---
# handlers file for roles/lighthause
- name: NGINX | Restarted service
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: ansible_facts.virtualization_type != "docker"